name: Call following Workflow

on: 
  workflow_call:
    inputs:
      workflow-to-call:
        type: string
        required: true
        default: ''
      remaining-workflows:
        type: string
        required: true
        default: ''

jobs:
  test:
    if: inputs.workflow-to-call == 'test'
    uses: ./.github/workflows/test.yml
    with:
      workflows-to-dispatch: ${{ inputs.remaining-workflows }}
  cleanup:
    if: inputs.workflow-to-call == 'cleanup'
    uses: ./.github/workflows/cleanup.yml