name: Cleanup

on: [workflow_dispatch, workflow_call]

jobs:
  opensut-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Message
        run: | 
          echo Hello from Cleanup Workflow!