name: Cleanup

on: 
  # workflow_dispatch:
  #   inputs:
  #     package:
  #       type: string
  #       description: Package name.
  #       required: true
  # workflow_call:
  #   inputs:
  #     package:
  #       type: string
  #       description: Package name.
  #       required: true
  workflow_run:
    workflows: [Test1]
    types:
      - completed
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Message
        run: | 
          echo Hello from Cleanup Workflow! Package Name: ${{inputs.package}}