name: Build

on: 
  workflow_dispatch:
    inputs:
      run-tests:
        type: boolean
        description: Run test workflow
        required: true
        default: true
      run-cleanup:
        type: boolean
        description: Run cleanup workflow
        required: true
        default: true
  workflow_call:
    inputs:
      run-tests:
        type: boolean
        description: Run test workflow
        required: true
        default: true
      run-cleanup:
        type: boolean
        description: Run cleanup workflow
        required: true
        default: true

env:
  TEST_WORKFLOW: ${{ inputs.run-tests && '"test", ' || '"a", '}}
  CLEANUP_WORKFLOW: ${{ inputs.run-tests && '"cleanup"' || '"b"'}}
  WORKFLOW_JSON_STRING: ''
  NEXT_WORKFLOW: ''

jobs:
  build-job:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Inputs
        run: |
          echo run-tests: ${{ inputs.run-tests}}
          echo run-cleanup: ${{ inputs.run-cleanup}}

      - name: Print Message
        run: | 
          echo Hello from Build Workflow! TEST_WORKFLOW: $TEST_WORKFLOW, CLEANUP_WORKFLOW: $CLEANUP_WORKFLOW

      - name: Print JSON String
        run: |
          echo JSON String: ${{ format('[{0}{1}]', env.TEST_WORKFLOW, env.CLEANUP_WORKFLOW) }}
          echo "WORKFLOW_JSON_STRING=${{ format('[{0}{1}]', '$TEST_WORKFLOW', '$CLEANUP_WORKFLOW') }}" >> $GITHUB_ENV

      - name: Extrakt Next Workflow and update list
        run: |
          echo JSON String from env Var: $WORKFLOW_JSON_STRING

          nextWorkflow="$(echo $WORKFLOW_JSON_STRING | jq -r '.[0]')";
          echo "$nextWorkflow";
          echo "NEXT_WORKFLOW=$nextWorkflow" >> "$GITHUB_ENV"

          remainingWorkflows="$(echo $WORKFLOW_JSON_STRING | jq -c 'del(.[0])')";
          echo "$remainingWorkflows";
          echo "WORKFLOW_JSON_STRING=$remainingWorkflows" >> "$GITHUB_ENV"

      - name: Print Next Workflow env Var
        run: |  
          echo Next Workflow from env Var: $NEXT_WORKFLOW
          echo Remaining Workflows from env Var: $WORKFLOW_JSON_STRING

  call-next-workflow:
    needs: build-job
    uses: ./.github/workflows/call-workflow.yml
    with:
      workflow-to-call: ${{github.env.NEXT_WORKFLOW}}
      remaining-workflows: ${{github.env.WORKFLOW_JSON_STRING}}
    secrets: inherit

    # needs: build-job
    # runs-on: [ubuntu-latest]
    # steps:
    # - name: Dispatch workflow
    #   uses: actions/github-script@v7
    #   with:
    #     github-token: ${{ github.token }}
    #     script: |
    #       console.log(core.getInput('foo'))
    #       await github.rest.actions.createWorkflowDispatch({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         workflow_id: 'test.yml',
    #         ref: '${{ github.ref_name }}',
    #         inputs: {
    #           workflows_to_dispatch: $WORKFLOW_JSON_STRING
    #         },
    #       })
       