name: Test1

on: 
  workflow_dispatch:
    inputs:
      package:
        type: string
        description: Package name.
        required: true
  workflow_call:
    inputs:
      package:
        type: string
        description: Package name.
        required: true

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Message
        run: | 
          echo Hello from Test1 Workflow! Package Name: ${{inputs.package}}