name: Test

on: 
  workflow_dispatch:
    inputs:
      workflows-to-dispatch:
        type: string
        description: JSON string containing a list of workflows to be dispatched.
        required: true
  workflow_call:
    inputs:
      workflows-to-dispatch:
        type: string
        description: JSON string containing a list of workflows to be dispatched.
        required: true
      # workflow-id:
      #   type: number
      #   description: Index of next workflow to be dispatched.
      #   required: true

env:
  WORKFLOW_JSON_STRING: ''
  NEXT_WORKFLOW: ''



jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Message
        run: | 
          echo Hello from Test Workflow!
      - name: Print Remaining Workflows
        run: |
          echo Workflows to dispatch: ${{inputs.workflows-to-dispatch}}
  
      - name: Extrakt Next Workflow and update list
        run: |
          nextWorkflow="$(echo ${{inputs.workflows-to-dispatch}} | jq -r '.[0]')";
          echo "$nextWorkflow";
          echo "NEXT_WORKFLOW=$nextWorkflow" >> "$GITHUB_ENV"

          remainingWorkflows="$(echo ${{inputs.workflows-to-dispatch}} | jq -c 'del(.[0])')";
          echo "$remainingWorkflows";
          echo "WORKFLOW_JSON_STRING=$remainingWorkflows" >> "$GITHUB_ENV"

      - name: Print Next Workflow env Var
        run: |  
          echo Next Workflow from env Var: $NEXT_WORKFLOW
          echo Remaining Workflows from env Var: $WORKFLOW_JSON_STRING
  
  # call-next-workflow:
  #   uses: ./.github/workflows/call-workflow.yml
  #   with:
  #     workflow-to-call: $NEXT_WORKFLOW
  #     remaining-workflows: $WORKFLOW_JSON_STRING
  #   secrets: inherit

